name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时同步一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Add upstream remote
        run: |
          git remote add upstream ${{ secrets.UPSTREAM_REPO_URL }}
          
      - name: Fetch upstream
        run: |
          git fetch upstream
          
      - name: Sync branch
        run: |
          git checkout main
          git merge upstream/main
          git push origin main